### ISSUE TITLE
API Documentation is 404

### ISSUE THREAD

**Issue by Moonmonkey-Beep** [exPHAT/SwiftBluetooth#2]
Hi, the link in the readme is incorrect.
https://swiftpackageindex.com/exPHAT/SwiftBluetooth/1.0.0/documentation/

Should be:

https://swiftpackageindex.com/exPHAT/SwiftBluetooth/0.1.0/documentation/

**Comment by exPHAT** [comment]
Ah yep, will be fixing with the 1.0.0 release here in https://github.com/exPHAT/SwiftBluetooth/pull/3

Thanks!
