### ISSUE TITLE
Include advertisement data and RSSI for discovered peripherals

### ISSUE THREAD

**Issue by sindresorhus** [exPHAT/SwiftBluetooth#4]
You are currently ignoring the values here: https://github.com/exPHAT/SwiftBluetooth/blob/69af89de1c25d96481a75e863d728cc3850e5daf/Sources/SwiftBluetooth/CentralManager/CentralManager%2Basync.swift#L35

But those values are useful. For example, the RSSI provided there is the only way to get the RSSI without connecting to a peripheral first.

Maybe add a `initialRSSI` and `advertisementData` property to `Peripheral`.

Would be nice if `advertisementData ` was a struct based on fetching these keys from the original advertisement data: https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/advertisement_data_retrieval_keys

On a sidenote: I think the RSSI should be returned as a Double, not NSNumber.

**Comment by Moonmonkey-Beep** [comment]
Yes, would be great to get this data.

**Comment by sindresorhus** [comment]
> For the struct, you're thinking off defining all the keys so you can access them with, say, peripheral.advertisementData.localNameKey instead of indexing the dictionary via CBAdvertisementDataLocalNameKey?

Yes
