### ISSUE TITLE
`.connect()` and `.scanForPeripherals()` should have a timeout duration parameter

### ISSUE THREAD

**Issue by sindresorhus** [exPHAT/SwiftBluetooth#7]
For example, if you try to use `.connect()` with a device that is offline, it will await forever.

**Comment by exPHAT** [comment]
I agree, a timeout parameter will be useful here. I do like the idea of an optional (or maybe even default) infinite timeout duration. Would let you write something like this:

```swift
try await central.connect(peripheral, timeout: .infinity)

// The next time `peripheral` is within range and connectable, run some code
try await peripheral.writeValue(someValue, for: .someCharacteristic)

//
central.cancelPeripheralConnection(peripheral)
```

**Comment by sindresorhus** [comment]
> or maybe even default

I'm not sure that's the best default. The duration could often be forever and could cause developer to accidentally make functions "hang" (which is what I did).

It's your decision, but my recommendation is to enforce the `timeout` parameter but without any default. That way the user has to make a decision on the behavior they want.

**Comment by exPHAT** [comment]
One of my goals for the project is to remain compatible with existing codebases using CoreBluetooth, so at first thought I don't like the idea of introducing required additional parameters.

Though I guess this library has 3 overloads for each method, the stock one, the callback-based one, and the async one. If this is only added to the callback & async methods it likely wouldn't break anyones projects that migrate over.

Let be think about this one for a bit.
